### ISSUE TITLE
Update footer

### ISSUE THREAD

**Issue by govtech-malaysia** [govtechmy/myds#3]
Things to do:

1. Remove address and social media.
2. Remove Disclaimer and Privacy Policy (keep all rights reserved)
3. For the "Open Source" tab, the GitHub and Figma should point to the GH and Figma for this project, NOT for the overall MYDS.
4. Add a new Tab in Footer called "Design System", under which you have two items: [Design Standards](https://standard.digital.gov.my) and [Figma (Beta)](https://www.figma.com/design/svmWSPZarzWrJ116CQ8zpV/MYDS-(Beta)?node-id=7-20696).

**Comment by jessesoomy** [comment]
1. Done
2. Done
3. They currently link to [GitHub Repo](https://github.com/govtechmy/myds) and [Figma](https://www.figma.com/design/svmWSPZarzWrJ116CQ8zpV/MYDS-(Beta)?node-id=7-20696&t=A1mfwrtKyez4lJjE-1")
4. Done
