### ISSUE TITLE
Cookie Banner suggestion

### ISSUE THREAD

**Issue by txz-169** [govtechmy/myds#80]
According to the [cookie banner design document](https://design.digital.gov.my/en/docs/design/cookies-banner), the "Accept all" and "Reject all" buttons at 2 and 8/9 serve different purposes despite having the same label, which might confuse users. Button 8 which is supposed to accept the cookies selected under the "Customize" settings should be labelled as "Save" or "Confirm my choices" while button 9 which is to reject all non-essential cookies should be labelled as "Necessary cookies only". 

Since necessary cookies are mandatory and cannot be unchecked, the checkbox at 5 should be greyed out (Disabled state) as specified by the [checkbox design document](https://design.digital.gov.my/en/docs/design/checkbox).

![image](https://github.com/user-attachments/assets/96acfe64-775d-4bd6-ab12-e94a2f42c693)

**Comment by sanbrons** [comment]
@txz-169, we appreciate your comment. Yes, you are right that the button's copy should be different to suit context in 'Customized Cookies Preference' state. We will make the necessary correction. Thank you. 🙏
