### ISSUE TITLE
Open discussion about this project.

### ISSUE THREAD

**Issue by rudzainy** [govtechmy/myds#92]
Assalamualaikum & salam sejahtera 👋 I am very interested in this project and was wondering if this Github Issues is the correct platform for the public to discuss the great stuff you guys are working on here, amongst other things under govtechmy.

Some things that is on my mind:

#### Design
1. IMO, using custom primary colour other than the one [specified in the guide](https://design.digital.gov.my/en/docs/design/color#primary) should be _highly discouraged_ for consistency, continuity and practical reasons. However, if the department/ agency etc argued with a compelling case, the colour should pass the WCAG Color Contrast test for both light and dark modes.
2. Having a guide for layout (or even better, templates!) will be very helpful.

#### Develop
1. It is critical for MYDS to also offer options for development with plain HTML CSS JS without any dependency on build tools. This can come at a later phase tho, when almost everything else has been finalised. 
2. Maybe even developing and maintaining our own CDN? Something to discuss further?

Looking forward to the official launch next year! 🚀

**Comment by irfancoder** [comment]
Waalaikumsalam, thank you for reaching out and yeah, you're in the right place. (Maybe this is better suited for the Discussions tab instead 😄) 

**Design**

> 1. IMO, using custom primary colour other than the one [specified in the guide](https://design.digital.gov.my/en/docs/design/color#primary) should be highly discouraged for consistency, continuity and practical reasons

Our stance on the **blue palette** is for it to serve as the default primary colour in MYDS, but not as the only colour. MYDS aims to be dynamic and capable of working with a wider option of colours (something that our product team is exploring as well in several of our products). We aim to be consistent while remain varied. But point taken on the WCAG colour contrast test! We should definitely define what colour CAN or CANNOT work with MYDS.

> 2. Having a guide for layout (or even better, templates!) will be very helpful.

Agree +1

**Develop**

> 1. It is critical for MYDS to also offer options for development with plain HTML CSS JS without any dependency on build tools. This can come at a later phase tho, when almost everything else has been finalised.

Personally this is something that I want to avoid going into, unless there is a significant take up in the developer market that would enjoy this option. We can have a separate discussion as to, but our current aim is to support the major JS framework/library in the ecosystem, such as React, Vue & Angular. 

> 2. Maybe even developing and maintaining our own CDN? Something to discuss further?

CDN for stylesheets? Web components? Care to share more?

**Comment by rudzainy** [comment]
> Maybe this is better suited for the Discussions tab instead 😄

Oh right! I'll post these kind of questions there in the future 👍

Thank you for your answers. Yeah I think we need to have more discussions with more local developers to be able to really get anything fruitful. I'll hold back my concerns till MYDS officially launch and gets more exposure among the dev community 🙂
